[advisories]
db-path = "$CARGO_HOME/advisory-dbs"
db-urls = ["https://github.com/RustSec/advisory-db"]
unmaintained = "workspace"
unsound = "workspace"
git-fetch-with-cli = true
ignore = [
    "RUSTSEC-2025-0141",
    "RUSTSEC-2026-0007",
    "RUSTSEC-2026-0009",
]

[licenses]
allow = [
    "0BSD",
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "BSL-1.0",
    "CDLA-Permissive-2.0",
    "CC0-1.0",
    "ISC",
    "Unicode-3.0",
    "Zlib",
    "MPL-2.0",
    "NCSA",
    "OpenSSL",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
