[package]
name = "rustok-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rustok-core.workspace = true
rustok-commerce.workspace = true
rustok-blog.workspace = true
rustok-content.workspace = true
rustok-forum.workspace = true
rustok-pages.workspace = true
rustok-tenant.workspace = true
rustok-rbac.workspace = true

loco-rs.workspace = true
tokio.workspace = true
axum.workspace = true
axum-extra = { version = "0.9", features = ["typed-header"] }
sea-orm.workspace = true
async-graphql.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true
base64.workspace = true
eyre = "0.6"
async-trait.workspace = true
thiserror.workspace = true
rust_decimal.workspace = true
argon2.workspace = true
hex.workspace = true
jsonwebtoken.workspace = true
password-hash.workspace = true
rand.workspace = true
sha2.workspace = true
moka = { workspace = true, features = ["future"] }
once_cell.workspace = true
utoipa = { workspace = true, features = ["axum_extras", "uuid", "chrono", "yaml"] }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }

# Loco extras
migration = { path = "migration" }

[dev-dependencies]
loco-rs = { workspace = true, features = ["testing"] }
serial_test = "3.1"

[package.metadata.cargo-udeps.ignore]
development = ["serial_test"]
