[package]
name = "rustok-server"
version.workspace = true
edition.workspace = true

[dependencies]
rustok-core.workspace = true
rustok-commerce.workspace = true
rustok-blog.workspace = true

loco-rs.workspace = true
tokio.workspace = true
axum.workspace = true
axum-extra = { version = "0.9", features = ["typed-header"] }
sea-orm.workspace = true
async-graphql.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true
base64.workspace = true
eyre = "0.6"
async-trait.workspace = true
thiserror.workspace = true
rust_decimal = "1.36"
argon2 = "0.5"
hex = "0.4"
jsonwebtoken = "9.3"
password-hash = "0.5"
rand = "0.8"
sha2 = "0.10"
moka = { version = "0.12", features = ["future"] }

# Loco extras
migration = { path = "migration" }

[dev-dependencies]
loco-rs = { workspace = true, features = ["testing"] }
serial_test = "3.1"
