[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
description.workspace = true
license.workspace = true

[dependencies]
toml = "1.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
