[build]
target = "index.html"
dist = "dist"
public_url = "/"

[watch]
ignore = ["./dist"]

[[hooks]]
stage = "build"
command = "tailwind-rs"
command_arguments = ["-i", "src", "-o", "dist/output.css", "--append", "input.css", "--minify"]

[[hooks]]
stage = "watch"
command = "tailwind-rs"
command_arguments = ["-i", "src", "-o", "dist/output.css", "--append", "input.css"]
