[package]
name = "rustok-telemetry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
once_cell.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
