[package]
name = "rustok-telemetry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
once_cell.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
prometheus = { version = "0.13", features = ["process"] }
lazy_static = "1.5"

# OpenTelemetry
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
tracing-opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
