[package]
name = "rustok-telemetry"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
once_cell.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
prometheus = { version = "0.14", features = ["process"] }
lazy_static = "1.5"
tokio.workspace = true

# OpenTelemetry
opentelemetry.workspace = true
opentelemetry-otlp = { workspace = true, features = ["trace", "grpc-tonic"] }
tracing-opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
