[package]
name = "rustok-storefront"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
leptos = { workspace = true, features = ["ssr"] }
serde = { workspace = true, features = ["derive"] }
