[package]
name = "rustok-storefront"
version.workspace = true
edition.workspace = true

[dependencies]
leptos.workspace = true
leptos_router.workspace = true
leptos_axum.workspace = true
axum.workspace = true
tokio.workspace = true
